/* DO NOT EDIT THIS FILE - it is machine generated */
#include "pch.h"
#include <jni.h>
/* Header for class shen_zhien_filestream_Write */

#ifndef _Included_shen_zhien_filestream_Write
#define _Included_shen_zhien_filestream_Write
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     shen_zhien_filestream_Write
	 * Method:    WriteFile
	 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
	 */
	JNIEXPORT jint JNICALL Java_shen_zhien_filestream_Write_WriteFile__Ljava_lang_String_2Ljava_lang_String_2I
	(JNIEnv*, jclass, jstring, jstring, jint);

	/*
	 * Class:     shen_zhien_filestream_Write
	 * Method:    WriteFile
	 * Signature: (Ljava/lang/String;II)I
	 */
	JNIEXPORT jint JNICALL Java_shen_zhien_filestream_Write_WriteFile__Ljava_lang_String_2II
	(JNIEnv*, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
