/* DO NOT EDIT THIS FILE - it is machine generated */
#include "pch.h"
#include <jni.h>
/* Header for class shen_zhien_filestream_Read */

#ifndef _Included_shen_zhien_filestream_Read
#define _Included_shen_zhien_filestream_Read
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     shen_zhien_filestream_Read
	 * Method:    ReadFile
	 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_shen_zhien_filestream_Read_ReadFile__Ljava_lang_String_2II
	(JNIEnv*, jclass, jstring, jint, jint);

	/*
	 * Class:     shen_zhien_filestream_Read
	 * Method:    ReadFile
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_shen_zhien_filestream_Read_ReadFile__Ljava_lang_String_2
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_Read
	 * Method:    EOF
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_Read_EOF__
	(JNIEnv*, jclass);

	/*
	 * Class:     shen_zhien_filestream_Read
	 * Method:    EOF
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_Read_EOF__Ljava_lang_String_2
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_Read
	 * Method:    ResetFile
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_shen_zhien_filestream_Read_ResetFile
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
