/* DO NOT EDIT THIS FILE - it is machine generated */
#include "pch.h"
#include <jni.h>
/* Header for class shen_zhien_filestream_FileTools */

#ifndef _Included_shen_zhien_filestream_FileTools
#define _Included_shen_zhien_filestream_FileTools
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    FileExists
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_FileTools_FileExists
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    DeleteFile
	 * Signature: (Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_shen_zhien_filestream_FileTools_DeleteFile
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    RenameFile
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_shen_zhien_filestream_FileTools_RenameFile
	(JNIEnv*, jclass, jstring, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    GetFileSize
	 * Signature: (Ljava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_shen_zhien_filestream_FileTools_GetFileSize
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    CreateDirectory
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_FileTools_CreateDirectory
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    IsDirectory
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_FileTools_IsDirectory
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    ListDirectory
	 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
	 */
	JNIEXPORT jobjectArray JNICALL Java_shen_zhien_filestream_FileTools_ListDirectory
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    CopyFile
	 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_FileTools_CopyFile
	(JNIEnv*, jclass, jstring, jstring, jboolean);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    GetLastModifiedTime
	 * Signature: (Ljava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_shen_zhien_filestream_FileTools_GetLastModifiedTime
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    CanRead
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_FileTools_CanRead
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    CanWrite
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_shen_zhien_filestream_FileTools_CanWrite
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    GetAbsolutePath
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_shen_zhien_filestream_FileTools_GetAbsolutePath
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    DeleteDirectory
	 * Signature: (Ljava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_shen_zhien_filestream_FileTools_DeleteDirectory
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     shen_zhien_filestream_FileTools
	 * Method:    CreateTempFile
	 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_shen_zhien_filestream_FileTools_CreateTempFile
	(JNIEnv*, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
